### ISSUE TITLE
Umm...

### ISSUE THREAD

**Issue by rust2** [EdrowsLuo/osu-lab#1]
Please update readme.md
Add screenshots, and etc.

**Comment by EdrowsLuo** [comment]
Umm...

**Comment by rust2** [comment]
Also add system requirements. It's will be good, because it isn't working on my phone and idk, why

**Comment by EdrowsLuo** [comment]
this game is still in early developing stage, so ui is not completed.
Current version is a test case, you should input the .osu file to test the game.

**Comment by rust2** [comment]
That is, for the game to start, I have to place the .osu file? Because, if I trying to launch game, I have black screen for ~0.5 second, and then it returns me back to the launcher.

(Sorry, if my english is bad)

//

Where is .apk?

**Comment by rust2** [comment]
I hope, that this game will be cool •_•

**Comment by EdrowsLuo** [comment]
i can speak English and Chinese.

**Comment by rust2** [comment]
Tell me pls, where I can get .apk?

**Comment by EdrowsLuo** [comment]
if you are developer, you can compile a apk yourself.
if not, wait for next release.

**Comment by rust2** [comment]
Why??

**Comment by EdrowsLuo** [comment]
issues means serious talking.
here isn't a free talking place....
